// generaTed by fileb0x at "2017-03-20 17:23:19.38831052 -0300 BRT" from config file "b0x.yaml"

package static

import (
	"log"
	"os"
)

// FileJsScript2Js is "js/script2.js"
var FileJsScript2Js = []byte("\x61\x6c\x65\x72\x74\x28\x27\x39\x31\x31\x27\x29\x3b\x0a")

func init() {

	f, err := FS.OpenFile(CTX, "js/script2.js", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		log.Fatal(err)
	}

	_, err = f.Write(FileJsScript2Js)
	if err != nil {
		log.Fatal(err)
	}

	err = f.Close()
	if err != nil {
		log.Fatal(err)
	}
}
