// generaTed by fileb0x at "2017-03-20 17:23:19.388890287 -0300 BRT" from config file "b0x.yaml"

package static

import (
	"log"
	"os"
)

// FileCSSStyle2CSS is "css/style2.css"
var FileCSSStyle2CSS = []byte("\x62\x6f\x64\x79\x20\x7b\x0a\x20\x20\x20\x20\x63\x6f\x6c\x6f\x72\x3a\x20\x72\x65\x64\x3b\x0a\x7d\x0a")

func init() {

	f, err := FS.OpenFile(CTX, "css/style2.css", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		log.Fatal(err)
	}

	_, err = f.Write(FileCSSStyle2CSS)
	if err != nil {
		log.Fatal(err)
	}

	err = f.Close()
	if err != nil {
		log.Fatal(err)
	}
}
