// generaTed by fileb0x at "2017-03-20 17:23:19.3886019 -0300 BRT" from config file "b0x.yaml"

package static

import (
	"log"
	"os"
)

// FileCSSStyle1CSS is "css/style1.css"
var FileCSSStyle1CSS = []byte("\x68\x74\x6d\x6c\x20\x7b\x0a\x20\x20\x20\x20\x62\x61\x63\x6b\x67\x72\x6f\x75\x6e\x64\x3a\x20\x62\x6c\x75\x65\x3b\x0a\x7d\x0a")

func init() {

	f, err := FS.OpenFile(CTX, "css/style1.css", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		log.Fatal(err)
	}

	_, err = f.Write(FileCSSStyle1CSS)
	if err != nil {
		log.Fatal(err)
	}

	err = f.Close()
	if err != nil {
		log.Fatal(err)
	}
}
